#!/bin/bash
echo Ive been called $1 times
export ME
while [ $(squeue -u $ME | wc -l) -gt 1 ]
do
    sleep 10
    echo wait
done
#./meta_meta_script_msweep_jade2
./meta_meta_script_msweep_jade3
sleep 1
if [ $1 -lt 10000 ]
then
    ./dank_meme $(($1+1))
fi
