#!/bin/bash

while read fun 
do
    echo $fun
    addqueue -m 2 ./meta_script_logQs $fun
done < <(sed "s/,/ /g" fake_10000_2_100_GP.txt)
#done < <(sed "s/,/ /g" fake_10000_2_mnist_FCN_1_0.2_GP.txt)
#done < <(sed "s/,/ /g" fake_10000_2_mnist_FCN_1_0.5_GP.txt)

