#!/bin/bash

export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/:/usr/local/lib/python3.5/dist-packages/"


m=10000 
dataset=mnist 
net=cnn 
L=4 
#net=resnet 
#L=32 
prefix=layer_sweep 
sigmaw=1.41421356237
sigmab=0.1
c=0

n_gpus=8
export n_gpus=$n_gpus

pool=max
for L in `seq 1 10`; do
    ./script2 --prefix $prefix --m $m --dataset $dataset --network $net --number_layers $L --training -sigmaw $sigmaw -sigmab $sigmab --confusion $c --n_gpus $n_gpus --compute_bound --pooling $pool --n_samples_repeats 5.0 --use_empirical_K
done

#pool=avg
#for L in `seq 1 10`; do
#    ./script2 --prefix $prefix --m $m --dataset $dataset --network $net --number_layers $L --training -sigmaw $sigmaw -sigmab $sigmab --confusion $c --n_gpus 8 --compute_bound --pooling $pool --n_samples_repeats 2.0 --use_empirical_K
#done
#
#pool=none
#for L in `seq 1 10`; do
#    ./script2 --prefix $prefix --m $m --dataset $dataset --network $net --number_layers $L --training -sigmaw $sigmaw -sigmab $sigmab --confusion $c --n_gpus 8 --compute_bound --pooling $pool --n_samples_repeats 2.0 #--use_empirical_K
#done

