#!/bin/bash

export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/:/usr/local/lib/python3.5/dist-packages/"

m=10000
#dataset=cifar
dataset=MNIST
net=cnn
L=4
prefix=pool_sweep_
sigmaw=1.0
sigmab=1.0

n_gpus=8
#n_gpus=1
export n_gpus=$n_gpus

c=0

net=$1
pool=$2

#for c in 0.7 0.8 0.9 1 2 3 4 5; do
#for net in vgg19 vgg16 resnet50 resnet101 resnet152 resnetv2_50 resnetv2_101 resnetv2_152 resnext50 resnext101 densenet121 densenet169 densenet201 mobilenetv2 nasnet; do 
#net=$1
#sigmaw=$2
echo $sigmaw
./script2 --prefix $prefix --m $m --dataset $dataset --network $net --number_layers $L --training --sigmaw $sigmaw --sigmab $sigmab --confusion $c --n_gpus $n_gpus --compute_bound --pooling $pool --n_samples_repeats 2.0 --use_empirical_K
