#!/bin/bash

#echo $PYTHONPATH
#export PYTHONPATH="$PYTHONPATH:/usr/local/lib/python3.5/dist-packages:~/.local/lib/"
#export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/"

#export PYTHONPATH="/home_directory/.local/lib/python2.7/site-packages/"

#py=/usr/bin/python3
#py=~/anaconda3/bin/python3
#py=/usr/bin/python3.6
py=python3
#py=python
export py=$py
export n_processes=1
number_inits=1

m=500
#dataset=mnist
#dataset=EMNIST
dataset=cifar
net=fc
L=1
#prefix=unbalancedt1_mnist_
prefix=test_
sigmaw=2.0
sigmab=0.0
pool=none
c=0.0
t=1

n_gpus=1
export n_gpus=$n_gpus

  #unblanced MNIST t=1
  # 93.5 uncentered L=1 b=0 (bound: 51.2) (MC bound: 68.8)
  # 91.7 uncentered L=2 b=0 (bound: 53.2) (MC bound: 69.8)
  # 91.7 uncentered L=4 b=0 (MC bound: 70.1)
  # 90.5 uncentered L=6 b=0 (bound: 56.3)
  # 91.9 uncentered L=2 b=1
  # 92.4 uncentered L=2 b=4
  # 91.7 uncentered L=2 b=6
  # 93.2 uncentered L=1 b=0.1
  # 92.5 uncentered L=1 b=0.5
  # 91.8 uncentered L=1 b=1 (bound: 56.3)
  # 92.5 uncentered L=1 b=4
  # 92.9 uncentered L=1 b=6
  # 92.5 uncentered L=1 b=7
  # 92.4 uncentered L=1 b=8
  # 91.8 centered L=1 b=0 (bound: 50.6)
  # 90.5 centered L=2 b=0
  # 90.1 centered L=4 b=0
  # 91.1 centered L=1 b=0.1
  # 91.3 centered L=1 b=0.5
  # 91.0 centered L=1 b=1.0

  #balanced EMNIST t=31
  #67. for centered L=6
  #67.6 for centered L=5
  #70. for uncentered L=6
  #70.2 for uncentered L=5
  #73. for centered L=1
  #72. for uncentered L=1

#for rep in `seq 1 8`; do
#echo $rep
#
#for L in `seq 1 1 8`; do
#echo $L
#
#for sigmab in 0.0 0.5 1.0 2.0; do
#echo $sigmab

  #./run_experiment --prefix $prefix --m $m --centering --threshold $t --dataset $dataset --network $net --number_layers $L --training --sigmaw $sigmaw --sigmab $sigmab --confusion $c --n_gpus $n_gpus --pooling $pool --number_inits $number_inits --n_samples_repeats 2.0 --boolfun_comp 35.0 --oversampling #--use_empirical_K --intermediate_pooling 1111 --intermediate_pooling_type none
  ./run_experiment --prefix $prefix --m $m --centering --threshold $t --dataset $dataset --network $net --number_layers $L --training --sigmaw $sigmaw --sigmab $sigmab --confusion $c --n_gpus $n_gpus --pooling $pool --number_inits $number_inits --n_samples_repeats 2.0 --boolfun_comp 35.0 #--use_empirical_K --intermediate_pooling 1111 --intermediate_pooling_type none
  #./run_experiment --prefix $prefix --m $m --threshold $t --dataset $dataset --network $net --number_layers $L --training --sigmaw $sigmaw --sigmab $sigmab --confusion $c --n_gpus $n_gpus --pooling $pool --number_inits $number_inits --n_samples_repeats 2.0 --boolfun_comp 35.0 #--use_empirical_K --intermediate_pooling 1111 --intermediate_pooling_type none

#done
#done
#done
