#!/bin/bash

#export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/:/usr/local/lib/python3.5/dist-packages/"

m=1000
#dataset=KMNIST
dataset=mnist
#net=vgg16 
net=cnn
L=4 
pool=none
prefix=new_comp_sweep_
sigmaw=2.0
sigmab=0.0

n_gpus=0
export n_gpus=$n_gpus
c=0


#for c in 0.7 0.8 0.9 1 2 3 4 5; do
#for c in 0.0 0.1 0.2 0.3 0.4 0.5; do
for c in 0.5; do
    #./run_experiment --prefix $prefix --m $m --dataset $dataset --network $net --number_layers $L --training -sigmaw $sigmaw -sigmab $sigmab --label_corruption $c --n_gpus $n_gpus --compute_bound --pooling $pool --n_samples_repeats 2.0 #--use_empirical_K
    ./run_experiment2 --prefix $prefix --m $m --dataset $dataset --network $net --number_layers $L --training -sigmaw $sigmaw -sigmab $sigmab --label_corruption $c --n_gpus $n_gpus --compute_bound --pooling $pool --n_samples_repeats 2.0 #--use_empirical_K
done
