#!/bin/bash

n=40
for dataset in mnist mnist-fashion EMNIST KMNIST cifar; do
    ./meta_script_msweep $dataset fc none $n
    ./meta_script_msweep $dataset cnn none $n
    ./meta_script_msweep $dataset cnn avg $n
    ./meta_script_msweep $dataset cnn max $n
done

n=50
for dataset in mnist mnist-fashion EMNIST KMNIST cifar; do
    for net in resnet50 resnet101 resnet152 resnetv2_50 resnetv2_101 resnetv2_152 resnext50 resnext101 densenet121 densenet169 densenet201 mobilenetv2 vgg19 vgg16 ; do 
        ./meta_script_msweep $dataset $net avg $n
    done
done

n=30
for dataset in mnist mnist-fashion EMNIST KMNIST cifar; do
    for net in nasnet; do 
        ./meta_script_msweep $dataset $net avg $n
    done
done

