#!/bin/bash

n=20
a=addqueue
#for dataset in mnist; do
#dataset=mnist
#$a -n $n -m 20 -s ./meta_script_msweep $dataset fc none $n
#dataset=EMNIST
#$a -n $n -m 100 -s ./meta_script_msweep $dataset fc none $n
dataset=mnist
#$a -n $n -m 3 -s ./meta_script_msweep $dataset fc none $n
$a -n 5 -m 120 -s ./meta_script_msweep $dataset fc none $n

#dataset=mnist
#$a -n $n -m 3 -s ./meta_script_msweep $dataset cnn max $n


#n=20
#a=addqueue
#dataset=mnist-fashion
#for net in resnet50 resnetv2_50 resnetv2_101 resnext50 resnext101 densenet121 densenet169 densenet201;
#do
#    $a -n $n -m 5 -s ./meta_script_msweep $dataset $net none $n
#done
