#!/bin/bash

#echo $PYTHONPATH
#export PYTHONPATH="$PYTHONPATH:/usr/local/lib/python3.5/dist-packages:~/.local/lib/"
#export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/"
#export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/:/usr/local/lib/python3.5/dist-packages/"
#export PYTHONPATH="~/.local/lib/python3.5/site-packages/"
#export PYTHONPATH="/home_directory/.local/lib/python2.7/site-packages/"
#export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/:/usr/local/lib/python3.5/dist-packages/"

#export TMP=/mnt/scratch/tmp
#export TMP=/tmp

#py=/usr/bin/python3
#py=~/anaconda3/bin/python3
#mpi=/users/guillefix/anaconda3/bin/mpiexec
#py=/usr/bin/python3.6
#py=python3
#py=python
py=/users/guillefix/anaconda3/envs/venv/bin/python
mpi=/users/guillefix/anaconda3/envs/venv/bin/mpiexec

#echo $n_gpus

$py generate_NN_arch.py $@
$py generate_inputs_sample.py $@

#
##/usr/local/shared/openmpi/4.0.0/bin/mpiexec -n 250 $py compute_kernel_and_bound.py $@
$mpi -n $n_procs $py compute_kernel.py $@
#
#/users/guillefix/anaconda3/bin/mpiexec -n 1 $py compute_kernel.py $@
#/users/guillefix/anaconda3/bin/mpiexec -n 250 $py compute_prob_and_bound.py $@ --num_post_samples 10000000 --cov_mult 0.1 --using_MC
#/users/guillefix/anaconda3/bin/mpiexec -n 15 $py compute_prob_and_bound.py $@ --num_post_samples 3200000 --cov_mult 0.33 --using_MC
#/users/guillefix/anaconda3/bin/mpiexec -n 1 $py compute_prob_and_bound.py $@ --using_EP

# # # /usr/local/shared/openmpi/4.0.0/bin/mpiexec -n 250 $py compute_prob_and_bound.py $@ --num_post_samples 100000 --cov_mult 0.5 --using_MC
#mpiexec -n $(nproc) $py compute_prob_and_bound.py $@ --num_post_samples 1600000 --cov_mult 0.7 --using_MC
#mpiexec -n $(nproc) $py compute_prob_and_bound.py $@ --num_post_samples 800000 --cov_mult 1.0 --using_MC
$mpi -n $n_procs $py compute_prob_and_bound.py $@ --using_EP
#/usr/local/shared/openmpi/4.0.0/bin/mpiexec -n 100 $py sample_funs.py $@ --number_samples 10000

#/users/guillefix/anaconda3/bin/mpiexec -n 1 $py NN_train.py $@

$mpi -n $n_procs $py NN_train.py $@
