#!/bin/bash

#export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/"

#py=/usr/bin/python3 
#py=~/anaconda3/bin/python3
py=python3

#echo $n_gpus

$py generate_NN_arch.py $@
$py generate_inputs_sample.py $@
#mpiexec -n $n_gpus $py compute_kernel_and_bound.py $@
#$py NN_train.py $@
