#!/bin/bash

#export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/:/usr/local/lib/python3.5/dist-packages/"
#export PYTHONPATH=""

m=1000
#dataset=cifar
dataset=KMNIST
#dataset=mnist
prefix=new_pool_sweep
prefix_suffix=new_pool_sweep
sigmaw=1.414
sigmaw=0.1
#sigmaw=5.0
#sigmab=0.0
n_gpus=1
optimizer=sgd
loss=ce
export n_gpus=$n_gpus

L=4
c=0
#pool=avg
#pool=none
net=cnn

#for pool in none; do 
for pool in none avg max; do 
    echo $pool
    prefix=${pool}_${prefix_suffix}
    if [ $pool = none ]; then
        intermediate_pooling=0000
    else
        intermediate_pooling=1111
    fi
        #./run_experiment2 --prefix $prefix --m $m --dataset $dataset --network $net --number_layers $L --training --sigmaw $sigmaw --sigmab $sigmab --label_corruption $c --n_gpus $n_gpus --pooling $pool --n_samples_repeats 0.01 --number_inits 1 --use_empirical_K --optimizer ${optimizer} --loss $loss --intermediate_pooling $intermediate_pooling $@
    addqueue -n 250 -m 10 -s './run_experiment --prefix '${prefix}' --m '${m}' --dataset '${dataset}' --network '${net}' --number_layers '${L}' --training --sigmaw '${sigmaw}' --sigmab '${sigmab}' --label_corruption '${c}' --n_gpus '${n_gpus}' --compute_bound --pooling '${pool}' --n_samples_repeats 0.1 --number_inits 1 --use_empirical_K --optimizer '${optimizer}' --loss '${loss}' --intermediate_pooling '${intermediate_pooling}

    #addqueue -n 25 -m 10 -s './run_experiment --prefix '${prefix}' --m '${m}' --dataset '${dataset}' --network '${net}' --number_layers '${L}' --training --sigmaw '${sigmaw}' --sigmab '${sigmab}' --label_corruption '${c}' --n_gpus '${n_gpus}' --compute_bound --pooling '${pool}' --n_samples_repeats 0.25 --number_inits 1 --use_empirical_K '
    #addqueue -n 250 -m 5 -s './run_experiment2 --prefix '${prefix}' --m '${m}' --dataset '${dataset}' --network '${net}' --number_layers '${L}' --training --sigmaw '${sigmaw}' --sigmab '${sigmab}' --label_corruption '${c}' --n_gpus '${n_gpus}' --compute_bound --pooling '${pool}' --n_samples_repeats 0.1 --number_inits 1 --use_empirical_K '
    #addqueue -n 1 -m 5 -s './run_experiment2 --prefix '${prefix}' --m '${m}' --dataset '${dataset}' --network '${net}' --number_layers '${L}' --training --sigmaw '${sigmaw}' --sigmab '${sigmab}' --label_corruption '${c}' --n_gpus '${n_gpus}' --compute_bound --pooling '${pool}' --n_samples_repeats 2.0 --number_inits 1 --use_empirical_K '
    #./run_experiment3 --prefix $prefix --m $m --dataset $dataset --network $net --number_layers $L --training --sigmaw $sigmaw --sigmab $sigmab --label_corruption $c --n_gpus $n_gpus --compute_bound --pooling $pool --n_samples_repeats 2.0 --number_inits 1 --use_empirical_K 
done
