#!/bin/bash

#nn=3x8
nn=1
#nn=90
n=$nn
#n=24
#mem=14
mem=20
#a='addqueue -q bigmem'
a=addqueue
#for dataset in mnist; do
#for dataset in mnist-fashion; do
#for dataset in mnist mnist-fashion EMNIST; do
#for dataset in KMNIST cifar; do
for dataset in mnist; do
    for net in resnet101 resnet152 resnetv2_50 resnetv2_101 resnetv2_152 resnext50 resnext101 densenet121 densenet169 densenet201 mobilenetv2 nasnet vgg19 vgg16 ; do 
    #for net in resnetv2_50 resnext50 densenet121 densenet169; do 
    #for net in nasnet; do 
        ./meta_script_msweep_process_Ks $dataset $net avg $n &
    done
    ./meta_script_msweep_process_Ks $dataset cnn none $n &
    ./meta_script_msweep_process_Ks $dataset cnn avg $n &
    ./meta_script_msweep_process_Ks $dataset cnn max $n &
done
for dataset in mnist mnist-fashion EMNIST KMNIST cifar; do
    for net in resnet50 resnet101 resnet152 resnetv2_50 resnetv2_101 resnetv2_152 resnext50 resnext101 densenet121 densenet169 densenet201 mobilenetv2 nasnet vgg19 vgg16 ; do 
    #for net in resnetv2_50 resnext50 densenet121 densenet169; do 
    #for net in nasnet; do 
        ./meta_script_msweep_process_Ks $dataset $net avg $n &
    done
    ./meta_script_msweep_process_Ks $dataset fc none $n &
    ./meta_script_msweep_process_Ks $dataset cnn none $n &
    ./meta_script_msweep_process_Ks $dataset cnn avg $n &
    ./meta_script_msweep_process_Ks $dataset cnn max $n &
done
wait
