#!/bin/bash

#for L in 15
for L in 2 5 10 15 20 30 40 50
do
    for sigmaw in `seq 1.0 0.1 2.5`
    #for sigmaw in `seq 1.0 0.1 2.1` 2.3 2.4 2.5
    #for sigmaw in 2.2
    do
        echo $L $sigmaw
        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
        #addqueue -m 2 -s -n 4 'meta_script_sigmasweep2 '$sigmaw' '$L
        addqueue -m 20 -s -n 50 'meta_script_sigmasweep2 '$sigmaw' '$L
  done
done

#for L in 2
#do
#    for sigmaw in `seq 1.0 0.1 2.5`
#    #for sigmaw in 1.0
#    do
#        echo $L $sigmaw
#        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#        addqueue -m 2 -s -n 4 'meta_script_sigmasweep2 '$sigmaw' '$L
#  done
#done

#for L in 15
#do
#    for sigmaw in 1.0
#    #for sigmaw in 1.0
#    do
#        echo $L $sigmaw
#        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#        addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#  done
#done
#
#for L in 20
#do
#    for sigmaw in 1.0 1.1
#    #for sigmaw in 1.0
#    do
#        echo $L $sigmaw
#        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#        addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#  done
#done
#
#for L in 30
#do
#    for sigmaw in 1.0
#    #for sigmaw in 1.0
#    do
#        echo $L $sigmaw
#        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#        addqueue -m 2 -s -n 4 'meta_script_sigmasweep2'$sigmaw' '$L
#  done
#done
##
#for L in 40
#do
#    for sigmaw in 1.0 2.3 2.4 2.5
#    #for sigmaw in 1.0
#    do
#        echo $L $sigmaw
#        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#        addqueue -m 2 -s -n 4 'meta_script_sigmasweep2'$sigmaw' '$L
#  done
#done
##
##
#for L in 50
#do
#    for sigmaw in 1.0 2.0 2.1 2.2 2.3 2.4 2.5
#    #for sigmaw in 1.0
#    do
#        echo $L $sigmaw
#        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#        addqueue -m 2 -s -n 4 'meta_script_sigmasweep2'$sigmaw' '$L
#  done
#done
#
#for L in 50
#do
#    for sigmaw in `seq 1.0 0.1 2.5`
#    do
#        echo $L $sigmaw
#        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#        addqueue -m 2 -s -n 4 'meta_script_sigmasweep2 '$sigmaw' '$L
#  done
#done
#for L in 40
#do
#    for sigmaw in 1.0 1.1 1.2 2.0 2.1 2.2 2.3 2.4 2.5
#    #for sigmaw in 1.0
#    do
#        echo $L $sigmaw
#        #addqueue -m 10 -s -n 4 'meta_script_sigmasweep '$sigmaw' '$L
#        addqueue -m 2 -s -n 4 'meta_script_sigmasweep2 '$sigmaw' '$L
#  done
#done
