#!/bin/bash

n=8
a='sbatch batch.sh '
#for dataset in mnist; do
for dataset in mnist mnist-fashion EMNIST KMNIST cifar; do
    for net in resnet50 resnet101 resnet152 resnetv2_50 resnetv2_101 resnetv2_152 resnext50 resnext101 densenet121 densenet169 densenet201 mobilenetv2 nasnet vgg19 vgg16 ; do 
        $a $dataset $net avg $n
    done
    $a $dataset fc none $n
    $a $dataset cnn none $n
    $a $dataset cnn avg $n
    $a $dataset cnn max $n
done
