#!/bin/bash

#nn=2x15
#nn=200
nn=1
n=$nn
#mem=10
#mem=10
#a=addqueue
for dataset in mnist; do
#for dataset in mnist-fashion; do
#for dataset in mnist mnist-fashion EMNIST KMNIST cifar; do
#for dataset in mnist mnist-fashion EMNIST; do
#for dataset in KMNIST cifar; do
    for net in resnet50 resnet101 resnet152 resnetv2_50 resnetv2_101 resnetv2_152 resnext50 resnext101 densenet121 densenet169 densenet201 mobilenetv2 nasnet vgg19 vgg16 ; do 
    #for net in resnetv2_50 resnext50 densenet121 densenet169; do 
    #for net in nasnet; do 
        ./meta_script_msweep $dataset $net avg $n
    done
    ./meta_script_msweep $dataset cnn none $n
    ./meta_script_msweep $dataset fc none $n
    ./meta_script_msweep $dataset cnn avg $n
    ./meta_script_msweep $dataset cnn max $n
done
