#!/bin/bash

for fun in $(cat "funs.txt" | cut -f2 -d' ');
do 
    echo $fun
    comp=$fun
    #cat results/${comp}_sgd_vs_bayes_generrs3__*_${comp}_64_40_2_1_sgd_ce_0_0.001_nn_training_results.txt > results/${comp}_sgd_vs_bayes_generrs3__64_40_2_1_sgd_ce_0_0.001_nn_training_results.txt
    #cat results/${comp}_sgd_vs_bayes_generrs3__*_${comp}_64_40_2_10_sgd_ce_0_0.001_nn_training_results.txt > results/${comp}_sgd_vs_bayes_generrs3__64_40_2_10_sgd_ce_0_0.001_nn_training_results.txt
    #cat results/${comp}_sgd_vs_bayes_generrs3__*_${comp}_64_40_2_10_sgd_ce_0_0.01_nn_training_results.txt > results/${comp}_sgd_vs_bayes_generrs3__64_40_2_10_sgd_ce_0_0.01_nn_training_results.txt
    #cat results/${comp}_sgd_vs_bayes_generrs3__*_${comp}_64_40_2_10_adam_ce_0_0.01_nn_training_results.txt > results/${comp}_sgd_vs_bayes_generrs3__64_40_2_10_adam_ce_0_0.01_nn_training_results.txt
    cat results/${comp}_sgd_vs_bayes_generrs3_nozeroone_sigmab0_adv__*_${comp}_64_40_2_10_sgd_ce_0_0.01_nn_training_results.txt > results/${comp}_sgd_vs_bayes_generrs3_nonfit__64_40_2_10_sgd_ce_0_0.01_nn_training_results.txt

done

#150.5_sgd_vs_bayes_generrs3_nozeroone_sigmab0_adv__63_150.5_64_40_2_10_sgd_ce_0_0.01_nn_training_results.txt
#results/147.0_sgd_vs_bayes_generrs3_nozeroone_sigmab0_adv__0_147.0_64_40_2_10_sgd_ce_0_0.01__0_nn_train_functions.txt
